#!/bin/bash

if [[ -f /etc/rc.d/init.d/functions ]]; then
source /etc/rc.d/init.d/functions
elif [[ -f /lib/lsb/init-functions ]]; then
source /lib/lsb/init-functions
fi

FOLDER="."
PID_FILE="/var/run/amstore.pid"
CMD="$FOLDER/run.sh"

function usage() {
	echo 'amstore start|stop|restart|status'
	exit 1
}

function start() {
     su amstore "$CMD"
     RETVAL=$?
#     ps -u amstore | grep 'start' | awk '{print $1}'  > /var/run/amstore.pid
#     ps -ef | grep -i amstore | grep start | grep -v grep | awk '{print $2}' > $PID_FILE
     return $RETVAL
}

function stop() {
      killproc -p $PID_FILE
      RETVAL=$?
      #kill -- -$(cat /var/run/amstore.pid)
      echo "" > /var/run/amstore.pid
      #rm -f $PID_FILE
      return $RETVAL
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		stop
		start
	;;
	status)
		ps -u amstore | grep 'start' | awk '{print $1}'  > /var/run/amstore.pid	
		#ps -ef | grep $(cat $PID_FILE) 2> /dev/null | grep -i amstore 
		RETVAL=$?
		if [[ $RETVAL == 0 ]]; then
		 echo 'Amstore is started.'
		else
		 echo 'Amstore is stopped.'
		fi
	;;
	*)
		usage
	;;
esac
